//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WKEFSERVICE.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://elite.etraining.gov.tw/lpf_wsv/get_data.asmx")]
        public string EUSERVICE_tw_gov_etraining_elite_get_data {
            get {
                return ((string)(this["EUSERVICE_tw_gov_etraining_elite_get_data"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://elite.etraining.gov.tw/bliws/get_pay.asmx")]
        public string EUSERVICE_tw_gov_etraining_elite1_get_pay {
            get {
                return ((string)(this["EUSERVICE_tw_gov_etraining_elite1_get_pay"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://elite.etraining.gov.tw/ELIT/WebService/WebTimeTable.asmx")]
        public string EUSERVICE_tw_gov_etraining_elite2_WebTimeTable {
            get {
                return ((string)(this["EUSERVICE_tw_gov_etraining_elite2_WebTimeTable"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://elite.etraining.gov.tw/ELIT/WebService/WebAbsence.asmx")]
        public string EUSERVICE_tw_gov_etraining_elite3_WebAbsence {
            get {
                return ((string)(this["EUSERVICE_tw_gov_etraining_elite3_WebAbsence"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://elite.etraining.gov.tw/ELIT/WebService/WebLeaveStatus.asmx")]
        public string EUSERVICE_tw_gov_etraining_elite4_WebLeaveStatus {
            get {
                return ((string)(this["EUSERVICE_tw_gov_etraining_elite4_WebLeaveStatus"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://yvtp.etraining.gov.tw/WebService/WebClass.asmx")]
        public string EUSERVICE_tw_gov_etraining_yvtp_WebClass {
            get {
                return ((string)(this["EUSERVICE_tw_gov_etraining_yvtp_WebClass"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://elite.etraining.gov.tw/trnapply/get_data.asmx")]
        public string EUSERVICE_tw_gov_etraining_elite5_get_data {
            get {
                return ((string)(this["EUSERVICE_tw_gov_etraining_elite5_get_data"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.70:9000/WebServices/WKEFSERVICE.asmx")]
        public string EUSERVICE_WebReference_EUSERVICE {
            get {
                return ((string)(this["EUSERVICE_WebReference_EUSERVICE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://wltims.wda.gov.tw/GetJobMail3/Service1.asmx")]
        public string EUSERVICE_tw_gov_wda_wltims_Service1 {
            get {
                return ((string)(this["EUSERVICE_tw_gov_wda_wltims_Service1"]));
            }
        }
    }
}
